backend:
  name: git-gateway
  branch: main

media_folder: "/public"
public_folder: "/public"
collections:
  - name : "blog"
    label: "Blog"
    folder: "/src/blog"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Featured Image", name: "image", widget: image}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }