backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "public/pictures/articles/analysis"
public_folder: "pictures/articles/analysis"
collections:
  - name : "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Featured Image", name: "image", widget: image}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
